name: 'finfocus-action'
description: 'Integrate pulumicost-core into CI/CD workflows for cloud cost estimates'
author: 'rshade'
inputs:
  pulumi-plan-json:
    description: 'Path to the pulumi preview --json output file'
    required: false
    default: 'plan.json'
  github-token:
    description: 'GitHub Token for posting comments'
    required: false
    default: ${{ github.token }}
  pulumicost-version:
    description: 'Version of pulumicost to install'
    required: false
    default: 'latest'
  install-plugins:
    description: 'Comma-separated list of plugins to install (e.g., aws-public)'
    required: false
    default: ''
  behavior-on-error:
    description: 'Behavior when an error occurs (fail, warn, silent)'
    required: false
    default: 'fail'
  post-comment:
    description: 'Whether to post a comment to the PR (true/false)'
    required: false
    default: 'true'
  fail-on-cost-increase:
    description: 'Threshold string (e.g., "100USD") to fail if diff exceeds'
    required: false
    default: ''
  analyzer-mode:
    description: 'If true, sets up environment for pulumi preview to use as analyzer'
    required: false
    default: 'false'
  detailed-comment:
    description: 'If true, provides a detailed breakdown of all resources and metadata in the PR comment'
    required: false
    default: 'false'
  log-level:
    description: 'Log level for pulumicost (debug, info, warn, error)'
    required: false
    default: 'error'
  debug:
    description: 'If true, enables detailed debug logging for the action itself'
    required: false
    default: 'false'
outputs:
  total-monthly-cost:
    description: 'The absolute projected monthly cost'
    value: ${{ steps.run.outputs.total-monthly-cost }}
  cost-diff:
    description: 'The difference in cost compared to the base state'
    value: ${{ steps.run.outputs.cost-diff }}
  currency:
    description: 'The currency code (e.g., USD)'
    value: ${{ steps.run.outputs.currency }}
  report-json-path:
    description: 'Path to the generated full JSON report'
    value: ${{ steps.run.outputs.report-json-path }}
  policy-pack-path:
    description: 'Path to the set up policy pack directory'
    value: ${{ steps.run.outputs.policy-pack-path }}
runs:
  using: 'composite'
  steps:
    - name: 'Run finfocus-action'
      id: run
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_PULUMI_PLAN_JSON: ${{ inputs.pulumi-plan-json }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_PULUMICOST_VERSION: ${{ inputs.pulumicost-version }}
        INPUT_INSTALL_PLUGINS: ${{ inputs.install-plugins }}
        INPUT_BEHAVIOR_ON_ERROR: ${{ inputs.behavior-on-error }}
        INPUT_POST_COMMENT: ${{ inputs.post-comment }}
        INPUT_FAIL_ON_COST_INCREASE: ${{ inputs.fail-on-cost-increase }}
        INPUT_ANALYZER_MODE: ${{ inputs.analyzer-mode }}
        INPUT_DETAILED_COMMENT: ${{ inputs.detailed-comment }}
        INPUT_LOG_LEVEL: ${{ inputs.log-level }}
        INPUT_DEBUG: ${{ inputs.debug }}
branding:
  icon: 'dollar-sign'
  color: 'blue'
