name: 'finfocus-action'
description: 'Integrate finfocus into CI/CD workflows for cloud cost estimates'
author: 'rshade'
inputs:
  pulumi-plan-json:
    description: 'Path to the pulumi preview --json output file'
    required: false
    default: 'plan.json'
  github-token:
    description: 'GitHub Token for posting comments'
    required: false
    default: ${{ github.token }}
  finfocus-version:
    description: 'Version of finfocus to install'
    required: false
    default: 'latest'
  install-plugins:
    description: 'Comma-separated list of plugins to install (e.g., aws-public)'
    required: false
    default: ''
  behavior-on-error:
    description: 'Behavior when an error occurs (fail, warn, silent)'
    required: false
    default: 'fail'
  post-comment:
    description: 'Whether to post a comment to the PR (true/false)'
    required: false
    default: 'true'
  fail-on-cost-increase:
    description: 'Threshold string (e.g., "100USD") to fail if diff exceeds'
    required: false
    default: ''
  analyzer-mode:
    description: 'If true, sets up environment for pulumi preview to use as analyzer'
    required: false
    default: 'false'
  detailed-comment:
    description: 'If true, provides a detailed breakdown of all resources and metadata in the PR comment'
    required: false
    default: 'false'
  include-recommendations:
    description: 'Include cost optimization recommendations in PR comment (true/false)'
    required: false
    default: 'true'
  log-level:
    description: 'Log level for finfocus (debug, info, warn, error)'
    required: false
    default: 'error'
  debug:
    description: 'If true, enables detailed debug logging for the action itself'
    required: false
    default: 'false'
  include-actual-costs:
    description: 'Include actual/historical costs in PR comment (true/false)'
    required: false
    default: 'false'
  actual-costs-period:
    description: 'Time period for actual costs: 7d, 30d, mtd (month-to-date), or custom YYYY-MM-DD'
    required: false
    default: '7d'
  pulumi-state-json:
    description: 'Path to Pulumi state JSON for state-based cost estimation'
    required: false
    default: ''
  actual-costs-group-by:
    description: 'Group actual costs by: resource, type, provider, daily, monthly'
    required: false
    default: 'provider'
  include-sustainability:
    description: 'Include carbon footprint and sustainability metrics (true/false)'
    required: false
    default: 'true'
  utilization-rate:
    description: 'Assumed utilization rate for sustainability calculations (0.0 to 1.0)'
    required: false
    default: '1.0'
  sustainability-equivalents:
    description: 'Show impact equivalents like trees, miles driven (true/false)'
    required: false
    default: 'true'
  fail-on-carbon-increase:
    description: 'Threshold (e.g., "10%", "10kg") to fail if carbon footprint increases'
    required: false
    default: ''
outputs:
  total-monthly-cost:
    description: 'The absolute projected monthly cost'
    value: ${{ steps.run.outputs.total-monthly-cost }}
  cost-diff:
    description: 'The difference in cost compared to the base state'
    value: ${{ steps.run.outputs.cost-diff }}
  currency:
    description: 'The currency code (e.g., USD)'
    value: ${{ steps.run.outputs.currency }}
  report-json-path:
    description: 'Path to the generated full JSON report'
    value: ${{ steps.run.outputs.report-json-path }}
  policy-pack-path:
    description: 'Path to the set up policy pack directory'
    value: ${{ steps.run.outputs.policy-pack-path }}
  actual-total-cost:
    description: 'Total actual cost for the specified period'
    value: ${{ steps.run.outputs.actual-total-cost }}
  actual-cost-period:
    description: 'The date range for actual costs (e.g., 2025-01-01 to 2025-01-07)'
    value: ${{ steps.run.outputs.actual-cost-period }}
  total-savings:
    description: 'Total potential monthly savings from recommendations'
    value: ${{ steps.run.outputs.total-savings }}
  recommendation-count:
    description: 'Total number of cost recommendations found'
    value: ${{ steps.run.outputs.recommendation-count }}
  total-carbon-footprint:
    description: 'Total estimated CO2 emissions (kgCO2e/month)'
    value: ${{ steps.run.outputs.total-carbon-footprint }}
  carbon-intensity:
    description: 'Carbon intensity per dollar spent (gCO2e/USD)'
    value: ${{ steps.run.outputs.carbon-intensity }}

runs:
  using: 'composite'
  steps:
    - name: 'Run finfocus-action'
      id: run
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_PULUMI_PLAN_JSON: ${{ inputs.pulumi-plan-json }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_FINFOCUS_VERSION: ${{ inputs.finfocus-version }}
        INPUT_INSTALL_PLUGINS: ${{ inputs.install-plugins }}
        INPUT_BEHAVIOR_ON_ERROR: ${{ inputs.behavior-on-error }}
        INPUT_POST_COMMENT: ${{ inputs.post-comment }}
        INPUT_FAIL_ON_COST_INCREASE: ${{ inputs.fail-on-cost-increase }}
        INPUT_ANALYZER_MODE: ${{ inputs.analyzer-mode }}
        INPUT_DETAILED_COMMENT: ${{ inputs.detailed-comment }}
        INPUT_INCLUDE_RECOMMENDATIONS: ${{ inputs.include-recommendations }}
        INPUT_LOG_LEVEL: ${{ inputs.log-level }}
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_INCLUDE_ACTUAL_COSTS: ${{ inputs.include-actual-costs }}
        INPUT_ACTUAL_COSTS_PERIOD: ${{ inputs.actual-costs-period }}
        INPUT_PULUMI_STATE_JSON: ${{ inputs.pulumi-state-json }}
        INPUT_ACTUAL_COSTS_GROUP_BY: ${{ inputs.actual-costs-group-by }}
        INPUT_INCLUDE_SUSTAINABILITY: ${{ inputs.include-sustainability }}
        INPUT_UTILIZATION_RATE: ${{ inputs.utilization-rate }}
        INPUT_SUSTAINABILITY_EQUIVALENTS: ${{ inputs.sustainability-equivalents }}
        INPUT_FAIL_ON_CARBON_INCREASE: ${{ inputs.fail-on-carbon-increase }}
branding:
  icon: 'dollar-sign'
  color: 'blue'
