import * as core from '@actions/core';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

import { ActionConfiguration, BudgetConfiguration, BudgetAlert } from './types.js';

export interface IConfigManager {
  writeConfig(config: ActionConfiguration): Promise<void>;
  writeScoringConfig(config: ActionConfiguration): Promise<void>;
}

export class ConfigManager implements IConfigManager {
  async writeConfig(config: ActionConfiguration): Promise<void> {
    const debug = config?.debug === true;

    // Validate budget amount
    if (!config.budgetAmount || config.budgetAmount <= 0) {
      core.warning('Budget amount is not configured or invalid. Skipping budget configuration.');
      return;
    }

    if (debug) {
      core.info('=== ConfigManager: Writing budget configuration ===');
      core.info(`  Budget amount: ${config.budgetAmount}`);
      core.info(`  Currency: ${config.budgetCurrency || 'USD'}`);
      core.info(`  Period: ${config.budgetPeriod || 'monthly'}`);
    }

    // Parse and validate inputs
    const budgetConfig = this.parseBudgetConfig(config);

    // Define config directory
    const configDir = path.join(os.homedir(), '.finfocus');
    if (debug) core.info(`  Config directory: ${configDir}`);

    // Create directory if it doesn't exist
    if (!fs.existsSync(configDir)) {
      if (debug) core.info('  Creating config directory...');
      fs.mkdirSync(configDir, { recursive: true });
    }

    // Generate YAML content
    const yamlContent = this.generateYaml(budgetConfig);

    // Write config file
    const configPath = path.join(configDir, 'config.yaml');
    if (debug) {
      core.info(`  Writing config to: ${configPath}`);
      core.info(`  Config content:\n${yamlContent}`);
    }

    fs.writeFileSync(configPath, yamlContent, 'utf8');

    if (debug) core.info('  Budget configuration written successfully');
    else core.info('Budget configuration created successfully');
  }

  /**
   * Opt in to Jev recommendation scoring. finfocus reads `scoring.enabled` and
   * `scoring.plugin` from ~/.finfocus/config.yaml. The action does not write
   * TYPESAFE_API_KEY; the workflow must pass that secret in the environment.
   * An existing scoring section is left unchanged.
   */
  async writeScoringConfig(config: ActionConfiguration): Promise<void> {
    if (!config.enableJevScoring) {
      return;
    }

    const configDir = path.join(os.homedir(), '.finfocus');
    const configPath = path.join(configDir, 'config.yaml');
    const block = [
      '# finfocus recommendation scoring',
      '# Generated by finfocus-action',
      'scoring:',
      '  enabled: true',
      '  plugin: jev',
      '  identifier_mode: pseudonymized',
      '',
    ].join('\n');

    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }

    if (!fs.existsSync(configPath)) {
      fs.writeFileSync(configPath, block, 'utf8');
      core.info('Jev scoring configuration created (scoring.plugin: jev)');
      return;
    }

    const existing = fs.readFileSync(configPath, 'utf8');
    if (/^scoring:/m.test(existing)) {
      core.info('scoring section already present in config.yaml; leaving it unchanged');
      return;
    }

    const separator = existing.endsWith('\n') ? '\n' : '\n\n';
    fs.writeFileSync(configPath, `${existing}${separator}${block}`, 'utf8');
    core.info('Jev scoring configuration appended (scoring.plugin: jev)');
  }

  private parseBudgetConfig(config: ActionConfiguration): BudgetConfiguration {
    const amount = config.budgetAmount || 0;
    const currency = config.budgetCurrency || 'USD';
    const period = this.validatePeriod(config.budgetPeriod || 'monthly');
    const alerts = this.parseAlerts(config.budgetAlerts);

    return {
      amount,
      currency,
      period,
      alerts,
    };
  }

  private validatePeriod(period: string): 'monthly' | 'quarterly' | 'yearly' {
    const validPeriods = ['monthly', 'quarterly', 'yearly'];
    if (!validPeriods.includes(period)) {
      core.warning(
        `Invalid budget period "${period}". Supported: ${validPeriods.join(', ')}. Defaulting to "monthly".`,
      );
      return 'monthly';
    }
    return period as 'monthly' | 'quarterly' | 'yearly';
  }

  private parseAlerts(alertsInput?: string): BudgetAlert[] {
    // Default alerts if none provided
    const defaultAlerts: BudgetAlert[] = [
      { threshold: 80, type: 'actual' },
      { threshold: 100, type: 'forecasted' },
    ];

    if (!alertsInput || alertsInput.trim() === '') {
      return defaultAlerts;
    }

    try {
      const parsed = JSON.parse(alertsInput) as BudgetAlert[];

      // Validate parsed alerts
      if (!Array.isArray(parsed)) {
        core.warning('Budget alerts must be an array. Using default alerts.');
        return defaultAlerts;
      }

      const validAlerts = parsed.filter((alert) => {
        if (typeof alert.threshold !== 'number' || alert.threshold <= 0) {
          core.warning(`Invalid alert threshold: ${alert.threshold}. Skipping.`);
          return false;
        }
        if (alert.type !== 'actual' && alert.type !== 'forecasted') {
          core.warning(
            `Invalid alert type: ${alert.type}. Must be "actual" or "forecasted". Skipping.`,
          );
          return false;
        }
        return true;
      });

      if (validAlerts.length === 0) {
        core.warning('No valid alerts found. Using default alerts.');
        return defaultAlerts;
      }

      return validAlerts;
    } catch (err) {
      core.warning(
        `Failed to parse budget alerts JSON: ${err instanceof Error ? err.message : String(err)}. Using default alerts.`,
      );
      return defaultAlerts;
    }
  }

  /**
   * Generate the finfocus config.yaml content.
   *
   * finfocus v0.4.0 reads budgets from `cost.budgets` using the scoped schema;
   * a top-level `budget:` key is ignored. The action writes a single `global`
   * budget so `cost projected` prints the BUDGET STATUS block and honors
   * `--exit-on-threshold`.
   */
  private generateYaml(config: BudgetConfiguration): string {
    const lines: string[] = [];

    lines.push('# finfocus budget configuration');
    lines.push('# Generated by finfocus-action');
    lines.push('');
    lines.push('cost:');
    lines.push('  budgets:');
    lines.push('    global:');
    lines.push(`      amount: ${config.amount.toFixed(2)}`);
    lines.push(`      currency: ${config.currency}`);
    lines.push(`      period: ${config.period}`);

    if (config.alerts && config.alerts.length > 0) {
      lines.push('      alerts:');
      for (const alert of config.alerts) {
        lines.push(`        - threshold: ${alert.threshold}`);
        lines.push(`          type: ${alert.type}`);
      }
    }

    lines.push('');
    return lines.join('\n');
  }
}
